"""
Newsletter Formatter Module
Formats newsletter content with proper HTML structure and styling
"""

from datetime import datetime
from typing import Optional


class NewsletterFormatter:
    """Formats newsletter content with Morning Brew-inspired styling"""

    @staticmethod
    def format_newsletter(
        content: str,
        newsletter_name: str,
        date: Optional[datetime] = None
    ) -> str:
        """
        Wrap newsletter content in a complete HTML template

        Args:
            content: The newsletter body content
            newsletter_name: Name of the newsletter
            date: Date for the newsletter (defaults to today)

        Returns:
            Complete HTML newsletter
        """
        if date is None:
            date = datetime.now()

        date_str = date.strftime("%B %d, %Y")
        day_of_week = date.strftime("%A")

        html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{newsletter_name} - {date_str}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #222;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}

        .container {{
            background-color: #ffffff;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}

        .header {{
            text-align: center;
            border-bottom: 3px solid #0066cc;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}

        .header h1 {{
            font-size: 32px;
            font-weight: bold;
            margin: 0;
            color: #0066cc;
        }}

        .date {{
            color: #666;
            font-size: 14px;
            margin-top: 10px;
        }}

        h1 {{
            color: #0066cc;
            font-size: 28px;
            margin-top: 30px;
            margin-bottom: 15px;
        }}

        h2 {{
            color: #0066cc;
            font-size: 22px;
            margin-top: 25px;
            margin-bottom: 12px;
            border-bottom: 2px solid #e0e0e0;
            padding-bottom: 8px;
        }}

        h3 {{
            color: #333;
            font-size: 18px;
            margin-top: 20px;
            margin-bottom: 10px;
            font-weight: 600;
        }}

        p {{
            margin: 12px 0;
            font-size: 16px;
            line-height: 1.7;
        }}

        ul {{
            margin: 15px 0;
            padding-left: 25px;
        }}

        li {{
            margin: 8px 0;
            font-size: 16px;
        }}

        a {{
            color: #0066cc;
            text-decoration: none;
            border-bottom: 1px solid #0066cc;
        }}

        a:hover {{
            color: #0052a3;
            border-bottom-color: #0052a3;
        }}

        .whats-brewing {{
            background-color: #f8f9fa;
            border-left: 4px solid #0066cc;
            padding: 20px;
            margin: 20px 0;
            border-radius: 4px;
        }}

        .whats-brewing h2 {{
            margin-top: 0;
            border-bottom: none;
        }}

        .story {{
            margin: 30px 0;
            padding: 20px 0;
            border-bottom: 1px solid #e0e0e0;
        }}

        .story:last-child {{
            border-bottom: none;
        }}

        .grab-bag {{
            background-color: #fff8e1;
            padding: 20px;
            border-radius: 4px;
            margin: 20px 0;
        }}

        .footer {{
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #e0e0e0;
            color: #666;
            font-size: 14px;
        }}

        strong {{
            color: #333;
            font-weight: 600;
        }}

        @media only screen and (max-width: 600px) {{
            .container {{
                padding: 20px;
            }}

            h1 {{
                font-size: 24px;
            }}

            h2 {{
                font-size: 20px;
            }}

            h3 {{
                font-size: 16px;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{newsletter_name}</h1>
            <div class="date">{day_of_week}, {date_str}</div>
        </div>

        {content}

        <div class="footer">
            <p>Generated by AI-Powered Newsletter Generator</p>
            <p>© {date.year} {newsletter_name}. All rights reserved.</p>
        </div>
    </div>
</body>
</html>"""

        return html_template

    @staticmethod
    def save_newsletter(html_content: str, output_path: str) -> None:
        """
        Save newsletter to file

        Args:
            html_content: Complete HTML newsletter
            output_path: Path to save the file
        """
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)

    @staticmethod
    def extract_subject_line(content: str) -> str:
        """
        Extract subject line from newsletter content

        Args:
            content: Newsletter HTML content

        Returns:
            Subject line text
        """
        # Look for common subject line patterns
        if '<h1>' in content:
            start = content.find('<h1>') + 4
            end = content.find('</h1>', start)
            if end > start:
                return content[start:end].strip()

        return "Your Daily Newsletter"
